image: elixir:1.9.0-alpine

cache:
  paths:
    - _build
    - deps

before_script:
  - mix local.hex --force
  - mix local.rebar --force

compile:
  stage: build
  script:
    - mix deps.get --only test
    - mix compile --warnings-as-errors

test:
  stage: test
  script:
    - mix test

lint:
  stage: test
  script:
    - mix format --check-formatted

pages:
  stage: deploy
  script:
  - mix deps.get
  - mix docs -o public
  artifacts:
    paths:
    - public
  only:
  - master
