image: elixir:alpine

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
  paths:
    - _build
    - deps

default:
  before_script:
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get

.compile_template: &compile_definition
  stage: build
  script:
    - mix compile --warnings-as-errors

.test_template: &test_definition
  stage: test
  script:
    - mix test --cover

.lint_template: &lint_definition
  stage: test
  script:
    - mix format --check-formatted --check-equivalent
    - mix credo --strict

compile:1.10:
  image: elixir:1.10-alpine
  <<: *compile_definition

compile:1.9:
  image: elixir:1.9-alpine
  <<: *compile_definition

compile:1.8:
  image: elixir:1.8-alpine
  <<: *compile_definition

compile:1.7:
  image: elixir:1.7-alpine
  <<: *compile_definition

test:1.10:
  image: elixir:1.10-alpine
  <<: *test_definition

test:1.9:
  image: elixir:1.9-alpine
  <<: *test_definition

test:1.8:
  image: elixir:1.8-alpine
  <<: *test_definition

test:1.7:
  image: elixir:1.7-alpine
  <<: *test_definition

lint:1.10:
  image: elixir:1.10-alpine
  <<: *lint_definition

lint:1.9:
  image: elixir:1.9-alpine
  <<: *lint_definition

lint:1.8:
  image: elixir:1.8-alpine
  <<: *lint_definition

lint:1.7:
  image: elixir:1.7-alpine
  <<: *lint_definition

pages:
  stage: deploy
  script:
  - mix deps.get
  - mix docs -o public
  artifacts:
    paths:
    - public
  only:
  - master
